# https://cloud.google.com/appengine/docs/standard/reference/app-yaml?tab=node.js#top

# https://cloud.google.com/sdk/docs/install-sdk#linux

# gcloud auth login --no-launch-browser

# gcloud app logs tail -s default

# gcloud app browse

# https://smooth-copilot-370012.ew.r.appspot.com

# [START app_yaml]

runtime: nodejs16
instance_class: F4_1G
automatic_scaling:
  max_instances: 1

# env_variables:
#   GAE_APPLICATION: ""
#   GAE_ENV: "standard"
#   GOOGLE_CLOUD_PROJECT: "" 
#   NODE_ENV: "production"

# [END app_yaml]